### ISSUE TITLE
[1.10.2] Crash with no other mods installed.

### ISSUE THREAD

**Issue by JAWSAWN** [TeamMD5/ProjectX#2]
I can't seem to make this mod work.
Getting this issue:
https://gist.github.com/JAWSAWN/12c1cdf1d6df26bc2597bc0aa75d9ad2
Forge:forge-1.10.2-12.18.2.2171.jar

**Comment by KitsuneAlex** [comment]
That is due to an outdated version of CodeChickenLib, i putted a warning in the lates download wich says to download the LATEST CodeChickenLib version from here: http://chickenbones.net/Pages/links.html

I'm sorry about the confusion but covers1624 didn't put the latest CCL version up on CurseForge yet.
Have fun playing with the mod ! =)

**Comment by JAWSAWN** [comment]
oh nice
